name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  workflow_dispatch:  # Manual trigger only
  #push:
    #branches:
     # - main
  #pull_request:
    #branches:
     # - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest
        run: |
          pip install pytest  # Directly install pytest if not in requirements.txt
           # Step 4: Run tests
      - name: Run tests
        run: |
          pytest test  # Specify the directory where your tests are located

  build:
    runs-on: ubuntu-latest
    needs: test  # This makes sure the 'build' job runs only after 'test' job succeeds

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: shwetakpadaki # Use your actual secret or uncomment it
        # Password or personal access token used to log against the Docker registry
        password: dckr_pat_kA1vZj3cvcMDefFTsNMxcAt1peM  # Use your actual secret or uncomment it
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shwetakpadaki/cd-demo:1.0

    - name: Push the Docker image
      run: docker push shwetakpadaki/cd-demo:1.0
