name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install transformers
        run: |
          pip install transformers  # Directly install pytest if not in requirements.txt

        
      - name: Install pytest
        run: |
          pip install pytest  # Directly install pytest if not in requirements.txt

      

      - name: Set PYTHONPATH for llm1 module
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Set PYTHONPATH to the src/ directory

      - name: Check PYTHONPATH
        run: echo $PYTHONPATH  # This will print PYTHONPATH to help debug

    

    # Step 4: Run tests
      - name: Run tests
        run: |
          PYTHONPATH=$(pwd)/src pytest test  # Run pytest with the correct PYTHONPATH

  
      
